#### SEND REQUEST TO UPDATE A PROFILE
PATCH  http://localhost:8080/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc1MDcxNDk1MSwiZXhwIjoxNzUwODAxMzUxfQ.COdsH-o63FezxYWU8N31qn6f9MnGAQk87HxjHx02LEU
Content-Type: application/json

{
  "username": "ayonz"
}


#### LOGIN A USER
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "aggeloskwn",
  "password": "http://localhost:8080/auth" 
}

#### FETCH LEADERBOARD
GET http://localhost:8080/api/games/leaderboard
Content-Type: application/json

#### FETCH BET OVERVIEW
GET http://localhost:8080/api/admin/betoverview
Content-Type: application/json

#### FETCH BRANDING
GET http://localhost:8080/api/admin/branding
Content-Type: application/json


#### UPDATE BRANDING
PUT http://localhost:8080/api/admin/branding
Content-Type: application/json

{
   "name": "99w3w3",
   "color": "#05566E"
}

